export enum CharacterizationTypeEnum {
  WORKSTATION = 'WORKSTATION',
  EQUIPMENT = 'EQUIPMENT',
  ACTIVITIES = 'ACTIVITIES',
  GENERAL = 'GENERAL',
  SUPPORT = 'SUPPORT',
  OPERATION = 'OPERATION',
  ADMINISTRATIVE = 'ADMINISTRATIVE',
}
