export enum EffectivenessStatusEnum {
  NOT_EVALUATED = 'NOT_EVALUATED',
  EFFECTIVE = 'EFFECTIVE',
  PARTIALLY_EFFECTIVE = 'PARTIALLY_EFFECTIVE',
  INEFFECTIVE = 'INEFFECTIVE',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}
