export enum CommentColumnsEnum {
  CHECK_BOX = 'CHECK_BOX',
  ORIGIN = 'ORIGIN',
  RECCOMENDATION = 'RECCOMENDATION',
  GENERATE_SOURCES = 'GENERATE_SOURCES',
  TEXT = 'TEXT',
  TYPE = 'TYPE',
  TEXT_TYPE = 'TEXT_TYPE',
  APPROVED = 'APPROVED',
  CHANGES = 'CHANGES',
  APPROVED_BY = 'APPROVED_BY',
  CREATED_BY = 'CREATED_BY',

  CREATED_AT = 'CREATED_AT',
  UPDATED_AT = 'UPDATED_AT',
}
