export enum ProfessionalTypeEnum {
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  DENTIST = 'DENTIST',
  SPEECH_THERAPIST = 'SPEECH_THERAPIST',
  TECHNICIAN = 'TECHNICIAN',
  ENGINEER = 'ENGINEER',
  USER = 'USER',
  OTHER = 'OTHER',
}
