export enum RoleEnum {
  MASTER = 'master',
  ADMIN = '0',
  USER = '1',
  PROFESSIONALS = '1.2',
  COMPANY = '2',
  EPI = '3',
  MANAGEMENT = '4',
  CONTRACTS = '4.1',
  PGR = '5',
  ACTION_PLAN = '5.1',
  CLINICS = '6',
  EXAM = '6.1',
  SCHEDULE_EXAM = '7',
  RISK = '8',
  DOCTOR = '10',

  DATABASE = '99',
  CHECKLIST = '98',
}
