export enum RoleEnum {
  MASTER = 'master',
  ADMIN = '0',
  USER = '1',
  COMPANY = '2',
  EPI = '3',
  CONTRACTS = '4.1',
  ACTION_PLAN = '5',
  CLINICS = '6',
  EXAM = '6.1',
  SCHEDULE_EXAM = '7',
  RISK = '8',
  DOCTOR = '10',
  NOTIFICATION = '11',
  SECURITY = '12',
  MEDICINE = '13',
  DOCUMENTS = '14',
  EMPLOYEE = '15',
  ESOCIAL = '16',

  DATABASE = '99',
  CHECKLIST = '98',
}
