export enum StatusEnum {
  ACTIVE = 'ACTIVE',
  DONE = 'DONE',
  PROGRESS = 'PROGRESS',
  PROCESSING = 'PROCESSING',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
  ERROR = 'ERROR',
  EXPIRED = 'EXPIRED',
  CANCELED = 'CANCELED',
}
