export enum ConsolidatedViewExclusionReasonEnum {
  NO_ACCESS = 'NO_ACCESS',
  NOT_DONE = 'NOT_DONE',
  DIFFERENT_FORM = 'DIFFERENT_FORM',
  INCOMPATIBLE_STRUCTURE = 'INCOMPATIBLE_STRUCTURE',
  NOT_SAME_GROUP = 'NOT_SAME_GROUP',
}
