export enum QueryKeyAbsenteeismEnum {
  ABSENTEEISM_EMPLOYEE_TOTAL = 'ABSENTEEISM_EMPLOYEE_TOTAL',
  ABSENTEEISM_HIERARCHY_TOTAL = 'ABSENTEEISM_HIERARCHY_TOTAL',
  ABSENTEEISM_TIMELINE_TOTAL = 'ABSENTEEISM_TIMELINE_TOTAL',
  ABSENTEEISM_TYPE_COUNT = 'ABSENTEEISM_TYPE_COUNT',
  ABSENTEEISM_DAYS_COUNT = 'ABSENTEEISM_DAYS_COUNT',
}
