export enum QueryKeyActionPlanEnum {
  ACTION_PLAN = 'V2_ACTION_PLAN',
  ACTION_PLAN_INFO = 'V2_ACTION_PLAN_INFO',
  ACTION_PLAN_COMMENT = 'V2_ACTION_PLAN_COMMENT',
  ACTION_PLAN_COORDINATORS = 'V2_ACTION_PLAN_COORDINATORS',
  ACTION_PLAN_RESPONSIBLES = 'V2_ACTION_PLAN_RESPONSIBLES',
  ACTION_PLAN_COMMENT_CREATORS = 'V2_ACTION_PLAN_COMMENT_CREATORS',
  ACTION_PLAN_HIERARCHIES = 'V2_ACTION_PLAN_HIERARCHIES',
}
