export enum QueryKeyCharacterizationEnum {
  CHARACTERIZATIONS = 'V2_CHARACTERIZATIONS',
  CHARACTERIZATIONS_STATUS = 'V2_CHARACTERIZATIONS_STATUS',

  PHOTO_RECOMMENDATION = 'V2_PHOTO_RECOMMENDATION',
}
