export enum QueryKeyCharacterizationEnum {
  CHARACTERIZATIONS = 'V2_CHARACTERIZATIONS',
  AI_CHARACTERIZATION_ASSIST_TRACES = 'V2_AI_CHARACTERIZATION_ASSIST_TRACES',
  PHOTO_RECOMMENDATION = 'V2_PHOTO_RECOMMENDATION',
}
