export enum QueryKeyFormEnum {
  FORM_APPLICATION = 'V2_FORM_APPLICATION',
  FORM_MODEL = 'V2_FORM_MODEL',
  PUBLIC_FORM_APPLICATION = 'V2_PUBLIC_FORM_APPLICATION',
  FORM_QUESTIONS_ANSWERS = 'V2_FORM_QUESTIONS_ANSWERS',
  FORM_QUESTIONS_ANSWERS_RISKS = 'V2_FORM_QUESTIONS_ANSWERS_RISKS',
  FORM_RISKS = 'V2_FORM_RISKS',
  FORM_APPLICATION_RISK_LOGS = 'V2_FORM_APPLICATION_RISK_LOGS',
}
