export enum QueryKeyEnum {
  CHARACTERIZATIONS = 'V2_CHARACTERIZATIONS',
  ACTION_PLAN = 'V2_ACTION_PLAN',
  ACTION_PLAN_INFO = 'V2_ACTION_PLAN_INFO',
  ACTION_PLAN_COORDINATORS = 'V2_ACTION_PLAN_COORDINATORS',
  STATUS = 'V2_STATUS',
}
