export enum SystemAiPromptKeyEnum {
  RISK_SOURCES_RECOMMENDATIONS = 'RISK_SOURCES_RECOMMENDATIONS',
  RISK_NARRATIVE_DIAGNOSTIC = 'RISK_NARRATIVE_DIAGNOSTIC',
  INDICATORS_NARRATIVE_ANALYSIS = 'INDICATORS_NARRATIVE_ANALYSIS',
  INDICATORS_NARRATIVE_DIAGNOSTIC = 'INDICATORS_NARRATIVE_DIAGNOSTIC',
  INDICATORS_NARRATIVE_DIAGNOSTIC_GROUPS_ONLY = 'INDICATORS_NARRATIVE_DIAGNOSTIC_GROUPS_ONLY',
  INDICATORS_NARRATIVE_DIAGNOSTIC_GROUPS_AND_QUESTIONS = 'INDICATORS_NARRATIVE_DIAGNOSTIC_GROUPS_AND_QUESTIONS',
}
