export const ChemicalProductRoutes = {
  LIST: 'v2/companies/:companyId/workspaces/:workspaceId/chemical-products',
  BY_ID: 'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/:productId',
  PURE_FROM_RISK:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/pure-from-risk',
  FROM_FISPQ:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/from-fispq',
  ARCHIVE:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/:productId/archive',
  RESTORE:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/:productId/restore',
  DELETION_ELIGIBILITY:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/:productId/deletion-eligibility',
  COMPOSITION:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/:productId/composition-versions',
  INGREDIENT_RISK_FACTOR:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/:productId/ingredients/:ingredientId/risk-factor',
  RISK_SEARCH:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/risk-factors/search',
  MANUFACTURERS:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/manufacturers',
  OCCUPATIONAL_ENRICH:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/occupational-enrich',
  OCCUPATIONAL_SEARCH_AUDIT_INCOMPLETE:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/occupational-search-audit/incomplete',
  UPLOAD_FILE:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/files',
  PARSE_FISPQ:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/fispq/parse',
  CREATE_FISPQ:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/:productId/fispq-documents',
  ACTIVATE_FISPQ:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/:productId/fispq-documents/:documentId/activate',
  PUBLISH_FISPQ:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/:productId/fispq-documents/:documentId/employee-visibility',
  ARCHIVE_FISPQ:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/:productId/fispq-documents/:documentId/archive',
  EXCEL_TEMPLATE:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/excel/template',
  EXCEL_EXPORT:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/excel/export',
  EXCEL_IMPORT_PREVIEW:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/excel/import/preview',
  EXCEL_IMPORT_COMMIT:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/excel/import/commit',
  EXCEL_PREPARE_ANALYZE:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/excel/prepare/analyze',
  EXCEL_PREPARE_EXPORT:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/excel/prepare/export',
  EXCEL_AI_CURATION_SUGGEST:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/excel/prepare/ai-curation/suggest',
  EXCEL_AI_CURATION_EXPORT:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/excel/prepare/ai-curation/export',
  EXCEL_AI_CURATION_OCCUPATIONAL_ENRICH:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/excel/prepare/ai-curation/occupational-enrich',
  EXCEL_VALIDATE_PREVIEW:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/excel/validate/preview',
  EXCEL_VALIDATE_EXPORT_CORRECTED:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/excel/validate/export-corrected',
  EXCEL_SURVEY_IMPORT_PREVIEW:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/excel/survey/import/preview',
  EXCEL_SURVEY_IMPORT_COMMIT:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/excel/survey/import/commit',
  USE_SCENARIOS:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-use-scenarios',
  USE_SCENARIO_BY_ID:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-use-scenarios/:scenarioId',
  USE_SCENARIOS_BY_PRODUCT:
    'v2/companies/:companyId/workspaces/:workspaceId/chemical-products/:productId/use-scenarios',
} as const;
