export enum ApiRoutesEnum {
  HIERARCHY = '/hierarchy',
  GHO = '/homogeneous-groups',
  EPI = '/epi',
  EMPLOYEES = '/employee',
  COMPANIES = '/company',
  DATABASE_TABLE = '/files/database-tables',
  DOWNLOAD_EMPLOYEES = '/files/company/download/unique',
  UPLOAD_EMPLOYEES = '/files/company/upload/unique',
  ME = '/users/me',
  SESSION = '/session',
  CHECKLIST = '/checklist',
  RISK = '/risk',
  RISK_DATA = '/risk-data',
  RISK_GROUP_DATA = '/risk-group-data',
  REC_MED = '/rec-med',
  GENERATE_SOURCE = '/generate-source',
}
