export enum CompanyActionEnum {
  WORKSPACE = 'WORKSPACE',
  HIERARCHY = 'HIERARCHY',
  HOMO_GROUP = 'HOMO_GROUP',
  EMPLOYEE = 'EMPLOYEE',
  PGR = 'PGR',
  RISKS = 'RISKS',
  COMPANY_RISKS = 'COMPANY_RISKS',
  USERS = 'USERS',
  DOCUMENTS = 'DOCUMENTS',
  EDIT = 'EDIT',
  RISK_GROUP = 'RISK_GROUP',
  CLINICS = 'CLINICS',
  EXAMS_RISK = 'EXAMS_RISK',
}

export enum ClinicActionEnum {
  USERS = 'USERS',
  EDIT = 'EDIT',
  PROFESSIONALS = 'PROFESSIONALS',
  EXAMS = 'EXAMS',
  DOCUMENTS = 'DOCUMENTS',
}
