export enum CompanyActionEnum {
  WORKSPACE = 'WORKSPACE',
  EMPLOYEE = 'EMPLOYEE',
  USERS = 'USERS',
  DOCUMENTS = 'DOCUMENTS',
  EDIT = 'EDIT',
  HIERARCHY = 'HIERARCHY',
  HOMO_GROUP = 'HOMO_GROUP',
  RISKS = 'RISKS',
  RISK_GROUP = 'RISK_GROUP',
  PGR = 'PGR',
  PCMSO = 'PCMSO',
  CLINICS = 'CLINICS',
  EXAMS_RISK = 'EXAMS_RISK',
  COMPANY_RISKS = 'COMPANY_RISKS',
  ABSENTEEISM = 'ABSENTEEISM',
  OS = 'OS',
  APPLY_SERVICE_COMPANY = 'APPLY_SERVICE_COMPANY',
}

export enum ClinicActionEnum {
  USERS = 'USERS',
  EDIT = 'EDIT',
  PROFESSIONALS = 'PROFESSIONALS',
  EXAMS = 'EXAMS',
  DOCUMENTS = 'DOCUMENTS',
  SCHEDULE_BLOCKS = 'SCHEDULE_BLOCKS',
}
