export enum IdsEnum {
  COMPANY_SELECT_NAVBAR = 'company-select-navbar',
  CANCEL_BUTTON = 'cancel-button',
  CONFIRM_BUTTON = 'confirm-button',
  INPUT_MENU_SEARCH = 'input-menu-search',
  INPUT_MENU_SEARCH_GHO_HIERARCHY = 'input-menu-search-gho-hierarchy',
  MENU_CLOSE = 'menu-close',
  CROP_IMAGE_BUTTON = 'crop-image-button',
  MENU_ITEM_ID = 'menu-item-:id',
  MENU_ITEM_CHECKBOX_ID = 'menu-item-checkbox-:id',
  RISK_SELECT = 'risk-select-id',
  EXAMS_SELECT_ID = 'exams-select-id',
  RISK_TOOL_GHO_HORIZONTAL = 'risk-tool-gho-horizontal-:id',
  HIERARCHY_MODAL_SELECT_ITEM = 'hierarchy-modal-select-item-:id',
  RISK_TOOL_GHO_INPUT_SEARCH = 'risk-tool-gho-input-search-id',
  ADD_PROFILE_CHARACTERIZATION_ID = 'add-profile-characterization-id',
  ADD_CHARACTERIZATION_ID = 'add-characterization-id',
  ADD_RISK_CHARACTERIZATION_ID = 'add-risk-characterization-id',
  EMPLOYEE_SELECT_ID = 'employee-select-id',
  EMPLOYEE_SCHEDULE_MEDICAL_EXAM_TYPE_CHECKBOX = 'schedule_medical_visit_table_checkbox_exam_type_:id',
}
