export enum ModalEnum {
  TREE_CARD = 'tree-card',
  PROBABILITY_ADD = 'probability-add',
  HIERARCHY_TREE_CARD = 'hierarchy-tree-card',
  USER_ADD = 'user-add',
  CHECKLIST_ADD = 'checklist-add',
  RISK_GROUP_ADD = 'risk-group-add',
  WORKSPACE_SELECT = 'workspace-select',
  RISK_GROUP_DOC_ADD = 'risk-group-doc-add',
  COMPANY_ADD = 'company-add',
  WORKSPACE_ADD = 'workspace-add',
  EMPLOYEES_ADD = 'employees-add',
  RISK_DATA_ADD = 'risk-data-add',
  RISK_ADD = 'risk-add',
  REC_MED_ADD = 'rec-med-add',
  EPI_ADD = 'epi-add',
  GHO_ADD = 'gho-add',
  GENERATE_SOURCE_ADD = 'generate-source-add',
  GLOBAL = 'global',
  UPLOAD = 'upload',
  TEST = 'test',
  HIERARCHIES_EXCEL_ADD = 'employees-excel-add',
}
