export enum ModalEnum {
  TREE_CARD = 'tree-card',
  HIERARCHY_TREE_CARD = 'hierarchy-tree-card',
  CHECKLIST_ADD = 'checklist-add',
  RISK_GROUP_ADD = 'risk-group-add',
  COMPANY_ADD = 'company-add',
  WORKSPACE_ADD = 'workspace-add',
  RISK_DATA_ADD = 'risk-data-add',
  RISK_ADD = 'risk-add',
  REC_MED_ADD = 'rec-med-add',
  EPI_ADD = 'epi-add',
  GHO_ADD = 'gho-add',
  GENERATE_SOURCE_ADD = 'generate-source-add',
  GLOBAL = 'global',
  UPLOAD = 'upload',
  TEST = 'test',
}
