export enum QueryEnum {
  RISK = 'risk',
  RISK_DATA = 'risk-data',
  RISK_GROUP_DATA = 'risk-group-data',
  RISK_GROUP_DOCS = 'risk-group-docs',
  GHO = 'gho',
  DATABASE_TABLE = 'database-table',
  CHECKLIST = 'checklist',
  HIERARCHY = 'hierarchy',
  EMPLOYEES = 'employees',
  COMPANIES = 'companies',
  COMPANY = 'company',
  EPIS = 'epis',
  CHECKLIST_DATA = 'checklist-data',
  REC_MED = 'rec-med',
  GENERATE_SOURCE = 'risk',
}
