export enum RoutesEnum {
  ACTION_PLAN = '/dashboard/empresas/:companyId/:workspaceId/plano-de-acao/:riskGroupId',
  CHARACTERIZATIONS = '/dashboard/empresas/:companyId/:workspaceId',
  CHECKLIST = '/dashboard/checklist',
  COMPANIES = '/dashboard/empresas',
  CLINICS = '/dashboard/clinicas',
  COMPANY = '/dashboard/empresas/:companyId',
  COMPANY_GROUP = '/dashboard/empresas/:companyId/grupos',
  DASHBOARD = '/dashboard',
  DATABASE = '/dashboard/dados',
  DND_TREE_DEMO = '/dashboard/test/dnd-tree',
  EMPLOYEES = '/dashboard/empresas/:companyId/empregados',
  HIERARCHY = '/dashboard/empresas/:companyId/hierarquia',
  LOGIN = '/',
  MANAGER_SYSTEM = '/dashboard/empresas/:companyId/gestao-sst',
  MODAL = '/dashboard/test/modal',
  ONBOARD = '/acesso',
  ONBOARD_NO_TEAM = '/acesso/empresa',
  ONBOARD_USER = '/acesso/usuario',
  PGR_DOCUMENT = '/dashboard/empresas/:companyId/documentos/pgr/:riskGroupId',
  PROFESSIONALS = '/dashboard/empresas/:companyId/profissionais/todos',
  PROFILE = '/dashboard/perfil',
  PUBLIC = '/publico',
  RISK_DATA = '/dashboard/empresas/:companyId/hierarquia?riskGroupId=:riskGroupId',
  TEAM = '/dashboard/equipe/:companyId',
  TEAM_GROUPS = '/dashboard/equipe/:companyId/grupos',
}
