export enum AbsenteeismColumnsEnum {
  WORKSPACE = 'WORKSPACE',
  DIRECTORY = 'DIRECTORY',
  MANAGEMENT = 'MANAGEMENT',
  SECTOR = 'SECTOR',
  SUB_SECTOR = 'SUB_SECTOR',
  OFFICE = 'OFFICE',
  SUB_OFFICE = 'SUB_OFFICE',
  TOTAL = 'TOTAL',
  TOTAL_DAYS = 'TOTAL_DAYS',
  AVARAGE_DAYS = 'AVARAGE_DAYS',
  HOMOGENEOUS_GROUP = 'HOMOGENEOUS_GROUP',
}
