export enum CharacterizationColumnsEnum {
  CHECK_BOX = 'CHECK_BOX',
  NAME = 'NAME',
  TYPE = 'TYPE',
  PHOTOS = 'PHOTOS',
  CREATED_AT = 'CREATED_AT',
  UPDATED_AT = 'UPDATED_AT',
  STAGE = 'STAGE',
  ORDER = 'ORDER',
  RISKS = 'RISKS',
  HIERARCHY = 'HIERARCHY',
  PROFILES = 'PROFILES',
}
