export enum TaskColumnsEnum {
  CHECK_BOX = 'CHECK_BOX',
  ID = 'ID',
  DESCRIPTION = 'ORIGIN',
  PRIORITY = 'PRIORITY',
  STATUS = 'STATUS',
  CREATED_BY = 'CREATED_BY',
  END_DATE = 'END_DATE',
  RESPONSIBLE = 'RESPONSIBLE',
  CREATED_AT = 'CREATED_AT',
  UPDATED_AT = 'UPDATED_AT',
}
