export enum FormQuestionTypeEnum {
  TEXT = 'TEXT',
  RADIO = 'RADIO',
  CHECKBOX = 'CHECKBOX',
  SELECT = 'SELECT',
  SHORT_TEXT = 'SHORT_TEXT',
  LONG_TEXT = 'LONG_TEXT',
  FREQUENCY = 'FREQUENCY',
  INTENSITY = 'INTENSITY',
  DATE = 'DATE',
  NUMBER = 'NUMBER',
}
