export enum DrawerItemsEnum {
  dashboard = 'dashboard',
  profile = 'profile',
  documents = 'documents',
  team = 'team',
  accessGroups = 'accessGroups',
  companyGroups = 'companyGroups',
  checklist = 'checklist',
  importExportData = 'importExportData',
  allCompaniesData = 'allCompaniesData',
  allClinicsData = 'allClinicsData',
  oneClinicsData = 'oneClinicsData',
  companiesData = 'companiesData',
  companyPage = 'companyPage',
  professionals = 'professionals',
  exams = 'exams',
  risks = 'risks',
  schedule = 'schedule',
  esocial = 'esocial',
  absenteeism = 'absenteeism',
  cat = 'cat',
  block = 'block',
  report = 'report',
  employee = 'employee',
  registers = 'registers',
  actions = 'acrions',
}
