import { SxProps, Theme } from '@mui/material/styles';

export const documentEditorV2SurfaceSx: SxProps<Theme> = {
  '& .ProseMirror': {
    outline: 'none',
    minHeight: 240,
    color: 'text.primary',
  },
  '& .doc-editor-v2-variable': {
    display: 'inline-flex',
    alignItems: 'center',
    maxWidth: '100%',
    px: 0.75,
    py: '1px',
    mx: '1px',
    borderRadius: '999px',
    border: '1px solid',
    borderColor: 'info.light',
    bgcolor: '#E3F2FD',
    color: 'info.dark',
    fontSize: '0.78em',
    fontWeight: 'inherit',
    fontStyle: 'inherit',
    textDecoration: 'inherit',
    lineHeight: 1.35,
    whiteSpace: 'nowrap',
    userSelect: 'all',
    verticalAlign: 'baseline',
  },
  '& .doc-editor-v2-variable--unknown': {
    borderColor: 'warning.light',
    bgcolor: '#FFF8E1',
    color: 'warning.dark',
    fontStyle: 'italic',
  },
  '& .doc-editor-v2-atom': {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    px: 1.25,
    py: 0.75,
    my: 1,
    borderRadius: 1,
    border: '1px solid',
    fontSize: 13,
    lineHeight: 1.35,
    userSelect: 'none',
    cursor: 'default',
  },
  '& .doc-editor-v2-atom-icon': {
    flexShrink: 0,
    fontSize: 14,
    lineHeight: 1,
  },
  '& .doc-editor-v2-atom-label': {
    fontWeight: 600,
  },
  '& .doc-editor-v2-atom--pagination': {
    borderColor: 'grey.400',
    bgcolor: 'grey.50',
    color: 'text.secondary',
  },
  '& .doc-editor-v2-atom--break': {
    justifyContent: 'center',
    my: 1.5,
    py: 0.5,
    border: 'none',
    bgcolor: 'transparent',
    position: 'relative',
    '&::before, &::after': {
      content: '""',
      flex: 1,
      height: 0,
      borderTop: '1px dashed',
      borderColor: 'grey.400',
    },
  },
  '& .doc-editor-v2-atom--landscape': {
    borderStyle: 'dashed',
  },
  '& .doc-editor-v2-atom--media': {
    borderColor: 'secondary.light',
    bgcolor: '#F3E5F5',
    color: 'secondary.dark',
  },
  '& .doc-editor-v2-atom--table': {
    borderColor: 'primary.light',
    bgcolor: '#E3F2FD',
    color: 'primary.dark',
  },
  '& .doc-editor-v2-atom--data': {
    borderColor: 'success.light',
    bgcolor: '#E8F5E9',
    color: 'success.dark',
  },
  '& .doc-editor-v2-atom--unknown': {
    borderColor: 'grey.500',
    bgcolor: 'grey.100',
    color: 'text.secondary',
  },
  '& [data-doc-caption]': {
    position: 'relative',
    my: 0.75,
    pl: 1.25,
    borderLeft: '3px solid',
    borderColor: 'grey.400',
    bgcolor: 'grey.50',
    '&::before': {
      content: 'attr(data-caption-label)',
      display: 'block',
      fontSize: 11,
      fontWeight: 700,
      color: 'text.secondary',
      letterSpacing: 0.2,
      mb: 0.25,
      userSelect: 'none',
    },
  },
  '& [data-doc-heading]': {
    fontWeight: 700,
    mt: 2,
    mb: 1,
  },
  '& [data-heading-number]::before': {
    content: 'attr(data-heading-number) " "',
  },
  '& [data-doc-paragraph]': {
    my: 0.75,
  },
  '& [data-doc-bullet]': {
    position: 'relative',
    my: 0.35,
    paddingLeft: 'var(--doc-bullet-text-indent, 40px)',
    '&::before': {
      content: '"•"',
      position: 'absolute',
      left: 'var(--doc-bullet-marker-left, 24px)',
    },
  },
};
