export enum FormModelColumnsEnum {
  NAME = 'NAME',
  DESCRIPTION = 'DESCRIPTION',
  TYPE = 'TYPE',
  ANONYMOUS = 'ANONYMOUS',
  SYSTEM = 'SYSTEM',
  SHAREABLE_LINK = 'SHAREABLE_LINK',

  CREATED_AT = 'CREATED_AT',
  UPDATED_AT = 'UPDATED_AT',
}
